name: Assign PR team labels
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setting labels
        uses: FiligranHQ/auto-label@1.0.0
        with:
          labels_by_organization: "{\"FiligranHQ\":[\"filigran team\"]}"